[package]
name = "moustache"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv = { version = "0.68", features = ["imgproc"] }
clap = { version = "3.1.*", features = ["derive"] }
